spring:
  profiles:
    active:
    - dev
    
---
server:
  port: 8801 
spring:
  profiles: dev
  application:
    name: microcloud-config-client
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1111/eureka   
info:
  app.name: mldn-microcloud-beta-3
  company.name: www.mldnjava.cn
  app.version: v-beta-1.5.2
---
server:
  port: 8802
spring:
  profiles: bate
  application:
    name: microcloud-config-client
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7301/eureka
info:
  app.name: mldn-microcloud-beta-3
  company.name: www.mldnjava.cn
  app.version: v-beta-3.5.2
      