spring:
  profiles:
    active:
    - dev
    
---
server:
  port: 8801 
spring:
  profiles: dev
  application:
    name: microcloud-config-client
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka   
---
server:
  port: 8802
spring:
  profiles: bate
  application:
    name: microcloud-config-client
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
      